baseURL = "https://tuo-username.github.io/mio-cv-hugo/"
languageCode = "en-us"
title = "CV di Lorenzo Reatini"
theme = ""

[outputs]
home = ["HTML"]
section = ["HTML"]
page = ["HTML", "PDF"]

[params]
pdf_output = "pdf/cv.pdf"
