baseURL = "https://jackgenius.github.io/markdown_cv/"
languageCode = "en-us"
title = "CV di Lorenzo Reatini"

[outputs]
home = ["HTML"]
section = ["HTML"]
page = ["HTML", "PDF"]

[params]
pdf_output = "pdf/cv.pdf"
